import os
import sys
import pandas as pd
from snakemake.utils import min_version

min_version("6.0")
shell.prefix(f"set -eo pipefail;")


include: "rules/common.smk"


df = read_sample_tbl()


include: "rules/reference_alignment.smk"
include: "rules/SafFire.smk"


wildcard_constraints:
    i="\\d+",
    sm="|".join(df.index) + "|" + "|".join(df["sample"].str.strip()),


rule all:
    input:
        expand(rules.aln_to_bed.output, sm=df.index, ref=config.get("ref").keys()),
        expand(rules.sam_to_paf.output, sm=df.index, ref=config.get("ref").keys()),
        expand(
            rules.trim_and_break_paf.output, sm=df.index, ref=config.get("ref").keys()
        ),
        expand(rules.SafFire.output, sm=df.index, ref=config.get("ref").keys()),
