temp_dir: temp
output_dir: results
logs_dir: logs
benchmarks_dir: benchmarks
ref:
  CHM13_V1.1: .test/ref.fa
sm:
  HG002: .test/HG002_1.fa.gz
  HG00733: .test/HG00733_1.fa.gz
aln_threads: 8
aln_mem: 30GB
mm_opts: "-x asm20 --secondary=no -s 25000 -K 8G"
break_paf: 5000
paired_aln_len: 250000
break_saffire: 5000
